type: object
additionalProperties: false

properties:
  user:
    $ref: '#/definitions/User'

definitions:
  User:
    type: object
    additionalProperties: false
    properties:
      name:
        type: string
